### PR TITLE
Add bazel support

### PR DESCRIPTION
**Pull request by earhart**

### CODE REVIEW

**Comment by schuhschuh** [comment]
Looks good to me besides the fact that ```genrules``` and compile options are "hard coded". As long as only UNIX is supported by Bazel I assume that's OK. Would be better if it w as more generic, though. No idea if that's because of limitations of Bazel or these BUILD rules only.

Anyway, I have no problem to merge as is. Thanks.

**Comment by earhart** [comment]
Bazel's Linux and OSX.  Bazel's rules are pretty configurable -- see http://bazel.io/docs/be/functions.html#select.  These definitions seem to work fine on modern-ish Linux; not sure about OSX, but it should be pretty straightforward to modify them if needed.

Thanks for taking the merge!  :-)

**Comment by schuhschuh** [comment]
@earhart Are you sure about the ```commit = ""``` in the WORKSPACE file to clone the current remote HEAD ? With Bazel version 0.2 I get an error that either tag or commit must be specified. It works when I specify a specific commit SHA. Also the online documentation of Bazel suggests that either one **must** be specified and it cannot be empty. Have you used a more recent version of Bazel ?

**Comment by schuhschuh** [comment]
Also, the provided ```BUILD``` file does not work on OS X.

```
ERROR: /private/var/tmp/_bazel_as12312/f65e755909a04a2fd88349acdf197944/external/gflags_git/BUILD:42:1: Executing genrule @gflags_git//:config_h failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
sed: illegal option -- r
```

On OS X, the correct flag is ```-E```.

To fix this, I have replaced the ```sed``` command by ```awk``` which does not require different flags on different Unix platforms.

A working example of a project that links to the gflags library with either build using CMake or Bazel is available [here](https://github.com/gflags/example).

**Comment by earhart** [comment]
For the WORKSPACE -- I apparently didn't word that well; my intention was
that the project using gflags should fill in the current HEAD commit SHA.
I don't know whether it's always been required, but it's definitely
required by whatever version I'm using.  :-)

Thanks for fixing the OS X issue!

)Rob

**Pull request merged**
