### PR TITLE
Bazel does not complain config.h cannot be found.

### PR DESCRIPTION
**Pull request by qzmfranklin**
This PR fixes the same issue that the PR below already fixed:
https://github.com/gflags/gflags/pull/150

### CODE REVIEW

**Comment by schuhschuh** [comment]
Hm, when or why does this error occur? I've tested it without and got no message. Could you provide more context to clarify why this should indeed be needed?

**Comment by schuhschuh** [comment]
Could it be related to [this PR change](https://github.com/gflags/gflags/commit/30dbc81fb5ffdc98ea9b14b1918bfe4e8779b26e) I've merged after I refactored the Bazel files myself?

**Comment by qzmfranklin** [comment]
Hi, thanks for the prompt reply.

Here is how to reproduce the error that this PR tried to solve:


1. Checkout this repo:
https://github.com/mzhaom/trunk

2. Update the git submodule under third_party/gflags/upstream to the HEAD of this official gflags repo.

3. Then running `bazel build third_party/gflags:gflags` would produce an error that indicates that the config.h file cannot be found.


This PR solves specifically the above mentioned problem.

**Comment by qzmfranklin** [comment]
Regarding the PR you mentioned, I have no clear idea. Probably, but not sure.

Admittedly, I am probably using gflags along a less tested path than using gflags as an external bazel repository.

**Comment by schuhschuh** [comment]
Thanks for clarifying. It appears to me related to the other open PR, see [my previous commit](https://github.com/gflags/gflags/pull/199#issuecomment-270889487). I don't think yours and these other reported uses of Bazel is how it's intended to work. You shouldn't have dependencies included within your project source tree via Git submodules. You should bind them as external dependencies and Bazel is responsible for downloading and building these when needed.

**Comment by schuhschuh** [comment]
BTW I just looked again at the previous PR's, and I think there is still quite a misunderstanding how to use Bazel properly. When I've rewritten the Bazel build, things seemed to be fine. I haven't looked at it since. Anyway, regarding adding `GENDIR` (as of PR #150 that you referenced), didn't seem to have been a good idea and was changed again afterwards (see PR #202). Hence, adding it back will just cause troubles again, I'm afraid.

**Comment by qzmfranklin** [comment]
Hi schuhschu,

Thanks a lot for the investigation and thoughtful reply. That is fair. I will keep it in mind.

Happy dragon boat's day~

**Comment by qzmfranklin** [comment]
Per the comments received from schuhschu, the problem solved by this PR is not in line with the recommended use model of gflags. Closing.

**Pull request closed without merging**
