### PR TITLE
Add MODULE.bazel file to support Bzlmod

### PR DESCRIPTION
**Pull request by Vertexwahn**
Add MODULE.bazel file to support Bzlmod

### CODE REVIEW

**Comment by Vertexwahn** [comment]
@aschuh-hf Any chance to get this merged?

**Comment by Vertexwahn** [comment]
@schuhschuh Is this repo dead? Or not in sync with the internal one?

**Comment by Mizux** [comment]
@Vertexwahn "internal" gflag is now part of abseil-cpp and IIRC this repo has been given to the community but it is not actively supported nor used by google...

ref: https://github.com/abseil/abseil-cpp/tree/master/absl/flags

**Comment by Vertexwahn** [comment]
@Mizux What is about glog? is this also now part of absiel?

**Comment by schuhschuh** [comment]
Dead is maybe a bit dramatic, but indeed there's the abseil fork that's supported by Google employees (though I suppose either library is probably considered relatively feature stable for many years by now). I left my thoughts on this in [a past comment](https://github.com/gflags/gflags/issues/307#issuecomment-655812036), which I should probably discuss more prominently on the front page someday.

I'm fine merging changes such as this one, but indeed my responsiveness has been lacking for years on this project. Unless there would be folks in the community who are really interested in and willing to develop the gflags library further (with more freedom than abseil), I would assume users to switch projects.

**Comment by Mizux** [comment]
> @Mizux What is about glog? is this also now part of abseil?

yes same story than gflags, but devil is in the details, so you may miss few API between absl and Glog/Gflags and it took several years after gflags to have glog dropped in absl (they want to rewrite/improve implem but without dedicated ressource, turn over it take time to see it landing in absl...).

AFAIK: protobuf, googletest, re2, pybind11, or-tools last release(s) should now depend on (i.e. use) abseil-cpp.

**Pull request merged**
