### PR TITLE
Hide config.h from rules that use gflags

### LINKED ISSUE #233: Bazel rule leaks config.h into projects that depend on it
Repro: main.cc can include config.h from gflags, even though it is not an allowed dependency (see [Header inclusion checking](https://docs.bazel.build/versions/master/be/c-cpp.html#hdrs)).

```
➜  cat WORKSPACE 
git_repository(
    name = "com_github_gflags_gflags",
    commit = "v2.2.1",
    remote = "https://github.com/gflags/gflags",
)
➜  cat BUILD 
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["@com_github_gflags_gflags//:gflags"],
)
➜  cat main.cc 
// this should fail
#include "config.h"

int main() {
  return 0;
}
➜  bazel build :main
INFO: Analysed target //:main (3 packages loaded).
INFO: Found 1 target...
Target //:main up-to-date:
  bazel-bin/main
INFO: Elapsed time: 4.626s, Critical Path: 1.30s
INFO: Build completed successfully, 5 total actions
```

Generating config.h into a different directory reduces the change that a user will accidentally include `config.h` from gflags.

```
➜  cat WORKSPACE 
git_repository(
    name = "com_github_gflags_gflags",
    commit = "c51da0b52466f7770d34d7d87bc26a5d2675baef",
    remote = "https://github.com/drigz/gflags",
)
➜  bazel build :main
INFO: Analysed target //:main (3 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/rodrigoq/git/bazeltest/config_h/BUILD:1:1: C++ compilation of rule '//:main' failed (Exit 1)
main.cc:2:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.613s, Critical Path: 0.16s
FAILED: Build did NOT complete successfully
```

I ran into this issue when converting ros/ros_comm to build with Bazel. I wasn't generating ros_comm's config.h, which meant that removing the dependency on glog/gflags broke the build, even though I was not using glog.

### PR DESCRIPTION
**Pull request by drigz**
Fixes #233. This should be safe because config.h is only included from .cc files (and from .h files that are in turn included from .cc files).

### CODE REVIEW

**Comment by drigz** [comment]
Don't merge this as is - it breaks the build when included from external workspaces, since `-I$(GENDIR)/glog_internal` is not the correct path.

**Comment by schuhschuh** [comment]
Hm, it was always intended to be hidden from dependent projects (see for example [this change](https://github.com/gflags/gflags/commit/30dbc81fb5ffdc98ea9b14b1918bfe4e8779b26e#diff-30a00d043c368888f8e4631b0ee7a23fL88)). I guess it is unclear which directories Bazel automatically adds to a dependent projects include path though these are not specified by the project as part of the public interface. At least I don't agree that Bazel should add `$(GENDIR)` to the include path of other projects by itself... 

Looking back at this previous PR that intended to fix the same, I am wondering if because of `gflags_h` and other rules that are specified as (public) `hdrs` of the library, Bazel adds the `GENDIR` of these rules which is identical to the `GENDIR` of `config.h`? Hence, the previous "fix" to move public headers to an `include` subdirectory was probably incorrect. Instead, the private headers needed to be moved. However, even that I think seems like a flaw in Bazel... there should be completely separate directory trees for public and private headers generated by a rule, not just an "internal" subdirectory.

Are you more familiar how Bazel manages include paths and separation of public and private header files? Or know where it is documented?

(... just got the don't merge yet messages...)

**Comment by schuhschuh** [comment]
Are `strip_include_prefix` and/or `include_prefix` be of any use, see [here](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library_args)?

**Comment by drigz** [comment]
I've added a messy fix, but let's ask bazel-discuss@ if there's a better way.

The understanding that I have comes from [Header inclusion checking](https://docs.bazel.build/versions/master/be/c-cpp.html#hdrs), where it says:

> Technically, the compilation of a .cc file may transitively include any header file in the hdrs or srcs in any cc_library in the transitive deps closure.

and

> Unfortunately Bazel currently cannot distinguish between direct and transitive inclusions, so it cannot detect error cases where a file illegally includes a header directly that is only allowed to be included transitively. [...] Currently, no error is produced in that case, but such error checking may be added in the future.

So I think Bazel can't easily detect this - it has to add the problematic `-I` flag to handle the case where you have:

```
cc_library(
    name = "lib",
    srcs=["internal.h", "lib.cc"],
    hdrs=["lib.h"],
)
internal.h is in genfiles
lib.h #includes internal.h (which is allowed)
```

**Comment by schuhschuh** [comment]
Have you had a look at `include_prefix`? The effect of it?

**Comment by drigz** [comment]
[I posted on bazel-discuss](https://groups.google.com/forum/#!topic/bazel-discuss/sZaQbxWQ6IY).

I haven't tried using `include_prefix` for this, but I've been using it elsewhere and I don't think it would help. It makes the headers accessible under a different path by creating a tree of symlinks and pointing to them from there, but I don't think it stops them being accessed by their previous repository-relative path.

**Comment by drigz** [comment]
Just tried adding:

```
diff --git a/bazel/gflags.bzl b/bazel/gflags.bzl
index cd0edad..acf1749 100644
--- a/bazel/gflags.bzl
+++ b/bazel/gflags.bzl
@@ -85,7 +85,8 @@ def gflags_library(hdrs=[], srcs=[], threads=1):
         name       = name,
         hdrs       = hdrs,
         srcs       = srcs,
-        includes   = ["include/"],
+        strip_include_prefix = "include/gflags",
+        include_prefix = "gflags",
         copts      = copts,
         linkopts   = linkopts,
         visibility = ["//visibility:public"]
```

to see if it would make config.h inaccessible, but no luck - it results in:

```
-iquote .
-iquote bazel-out/local-fastbuild/genfiles
-iquote external/com_github_gflags_gflags
-iquote bazel-out/local-fastbuild/genfiles/external/com_github_gflags_gflags
-iquote external/bazel_tools
-iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools
-Ibazel-out/local-fastbuild/bin/external/com_github_gflags_gflags/_virtual_includes/gflags
```

`_virtual_includes` is added by `*include_prefix`, but it doesn't remove `genfiles/external/com_github_gflags_gflags`. As far as I'm aware, `copts` is the only way to have a different include path for .cc files in this rule than for .cc files in rules that depend on this.

**Comment by schuhschuh** [comment]
I feel Bazel's automatic addition of unwanted paths to the include path of an external project and the inability to mark outputs of a `genrule` as private (at least not documented), and considering that the rule for "configuring" `config.h` isn't really needed, it appears easier to just get rid of the rule in the first place? See #235.

**Comment by schuhschuh** [comment]
> I haven't tried using include_prefix for this, but I've been using it elsewhere and I don't think it would help. It makes the headers accessible under a different path by creating a tree of symlinks and pointing to them from there, but I don't think it stops them being accessed by their previous repository-relative path.

Yes, I've played with it myself now to see what it does. Interestingly, even though the `-iquote` path to the generated files without the prefix is still passed to the compiler (wrapper), I couldn't include `gflags.h` without the `gflags/` prefix, though, just as intended. But this only worked for the public `hdrs` of the library. As you noted, it doesn't prevent `config.h` from being included.

**Comment by schuhschuh** [comment]
@drigz Thanks for bringing up the issue and providing a solution. I've merged the PR that instead avoids a `genrule` for a private header file.

**Pull request closed without merging**
