### PR TITLE
support sudo make uninstall

### PR DESCRIPTION
**Pull request by jasjuang**
This features reduces the pain of having to remove the installed libraries and headers in /usr/local/ one by one.

Before this change, after sudo make install 

``````
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libgflags.a
-- Installing: /usr/local/lib/libgflags_nothreads.a
-- Installing: /usr/local/include/gflags/gflags.h
-- Installing: /usr/local/include/gflags/gflags_declare.h
-- Installing: /usr/local/include/gflags/gflags_completions.h
-- Installing: /usr/local/include/gflags/gflags_gflags.h
-- Installing: /usr/local/lib/cmake/gflags/gflags-config.cmake
-- Installing: /usr/local/lib/cmake/gflags/gflags-config-version.cmake
-- Old export file "/usr/local/lib/cmake/gflags/gflags-targets.cmake" will be replaced.  Removing files [/usr/local/lib/cmake/gflags/gflags-targets-release.cmake].
-- Installing: /usr/local/lib/cmake/gflags/gflags-targets.cmake
-- Installing: /usr/local/lib/cmake/gflags/gflags-targets-release.cmake
-- Installing: /usr/local/bin/gflags_completions.sh
-- Installing: /usr/local/lib/pkgconfig/gflags.pc
-- Installing: /home/jasjuang/.cmake/packages/gflags/e5f7ce61772240490d3164df06f58ce9
``````

there is no easy ways to remove these files, but with this change we can simply type sudo make uninstall and

``````
Scanning dependencies of target uninstall
/usr/local
-- Uninstalling /usr/local/lib/libgflags.a
-- Uninstalling /usr/local/lib/libgflags_nothreads.a
-- Uninstalling /usr/local/include/gflags/gflags.h
-- Uninstalling /usr/local/include/gflags/gflags_declare.h
-- Uninstalling /usr/local/include/gflags/gflags_completions.h
-- Uninstalling /usr/local/include/gflags/gflags_gflags.h
-- Uninstalling /usr/local/lib/cmake/gflags/gflags-config.cmake
-- Uninstalling /usr/local/lib/cmake/gflags/gflags-config-version.cmake
-- Uninstalling /usr/local/lib/cmake/gflags/gflags-targets.cmake
-- Uninstalling /usr/local/lib/cmake/gflags/gflags-targets-release.cmake
-- Uninstalling /usr/local/bin/gflags_completions.sh
-- Uninstalling /usr/local/lib/pkgconfig/gflags.pc
-- Uninstalling /home/jasjuang/.cmake/packages/gflags/e5f7ce61772240490d3164df06f58ce9
Built target uninstall
``````

### CODE REVIEW

**Comment by schuhschuh** [comment]
Thanks, note however that this requires you to keep the build tree around.

You may also check out [this file](https://github.com/cmake-basis/modules/blob/master/uninstall/CMakeLists.txt) of my CMake BASIS project modules. It contains code to also install the manifest of installed files next to the package configuration file, i.e., `gflags-config.cmake` in this case. A simple invocation of `cmake` with a `-P` script can then be used to remove the files also when the build tree has been deleted already. But given that `gflags` is more likely to be installed in a system location such as `/usr/local` by a binary package rather than from a custom source built, I don't think it's needed for this project. If you don't install `gflags` using a binary package manager, I would rather assume that the installation is skipped altogether and the library be linked statically instead or as part of your project installation to not cause troubles with official `gflags` binary packages...

So I guess this change is just a handy thing for developers while they test some code. Otherwise I don't see any good use case for it. Fine by me to merge it, though.

**Comment by schuhschuh** [comment]
Actually, just a minor modification request. Could you move the `cmake_uninstall.cmake.in` template file to the `cmake` folder? Also, please format the snippet added to `CMakeLists.txt` in the same way as the rest of the CMake code in there for some consistency even if no coding style is documented.

**Comment by schuhschuh** [comment]
Finally, please add the `uninstall` target only when `NOT GFLAGS_IS_SUBPROJECT`.

**Comment by jasjuang** [comment]
@schuhschuh Updated based on your comments. Not entirely sure what kind of coding style you are referring to, so I adjusted the indention and brackets a bit. Feel free to commit on top of this PR.

**Pull request merged**
