### PR TITLE
Fix CMake macro special variable usage

### PR DESCRIPTION
**Pull request by randomguy3**
The argument-related variables in a macro body are not real variables,
but special substitutions. They cannot be directly referred to by name,
only expanded.

### CODE REVIEW

**Comment by schuhschuh** [comment]
Thanks, but have you tested it before and after? In CMake's `if` command, you can use the variable name without expanding it. See https://cmake.org/cmake/help/v3.8/command/if.html.

**Comment by schuhschuh** [comment]
You might refer to [CMP0054 ](https://cmake.org/cmake/help/v3.8/policy/CMP0054.html#policy:CMP0054) which tries to retrospectively fix some issues with this automatic variable expansion. However, given these functions are used internally only, have you had a specific issue with it, e.g., a warning with newer CMake versions?

**Comment by schuhschuh** [comment]
> "CMake 3.1 and above no longer implicitly dereference variables [...]"

I guess that explains the need for the change when following the `NEW` convention.

**Comment by randomguy3** [comment]
This is specifically in macros - see the [CMake macro documentation](https://cmake.org/cmake/help/v3.8/command/macro.html).

I discovered the problem when working on grpc/grpc#11140 - because of this issue, gflags was being installed when built as a submodule of gRPC. This change fixes that behaviour.

**Comment by randomguy3** [comment]
I did try to explain that `ARGC` was an unusual case in the comment I added (although I didn't add a similar comment next to the `property` variable dereference). Should I try and reword that to make it clearer?

**Comment by schuhschuh** [comment]
> I did try to explain that ARGC was an unusual case in the comment I added

Thanks, I've seen the comment but wasn't paying attention to the fact that it's a `macro`. I generally avoid them, but in this case I felt it would be the more efficient choice despite these downsides compared to a `function`. I see the reason for the changes now.

**Pull request merged**
